config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/masters', as: 'rails_admin'

  root :to => "sessions#new"
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  resources :sessions, only: [:new, :create, :destroy]

  resources :products
  get '/my-account' => 'my_account#show'
  get '/pos-invoices/get-voucher-sequences' => 'pos_invoices#get_voucher_sequences'

  get '/inventory-out-vouchers/get-voucher-sequences' => 'inventory_out_vouchers#get_voucher_sequences'
  get '/inventory-out-vouchers/get-business-entities' => 'inventory_out_vouchers#get_business_entities'

  get '/inventory-in-vouchers/get-voucher-sequences' => 'inventory_in_vouchers#get_voucher_sequences'
  get '/inventory-in-vouchers/get-business-entities' => 'inventory_in_vouchers#get_business_entities'
  get '/inventory-internal-transfer-vouchers/get-voucher-sequences' => 'inventory_internal_transfer_vouchers#get_voucher_sequences'
  get '/inventory-internal-transfer-vouchers/get-entity-locations' => 'inventory_internal_transfer_vouchers#get_entity_locations'

  get '/inventory-transactions/summary-report' => 'inventory_txn_reports#index'

  get '/pos-invoice-payments' => 'pos_invoices#payment'

  resources :pos_invoices, path: 'pos-invoices'
  get 'pos-invoices-list-with-payment' => 'pos_invoices_reports#pos_invoices_list_with_payment'
  get 'pos-invoices-line-items' => 'pos_invoices_reports#pos_invoice_line_items'
  resources :inventory_out_vouchers, path: 'inventory-out-vouchers'
  resources :inventory_in_vouchers, path: 'inventory-in-vouchers'
  resources :inventory_internal_transfer_vouchers, path: 'inventory-internal-transfer-vouchers'
  get 'inventory-internal-transfer-vouchers-line-items' => 'inventory_txn_vouchers_reports#inventory_internal_transfer_vouchers_line_items'
  resources :journal_vouchers, path: 'journal-vouchers'

  resources :users

  get '/sales-report' => 'reports#sales'
  get '/payment-collection' => 'reports#payment_collection'
  get '/stock-summary' => 'inventory_reports#stock_summary'
  get '/invoices-pending' => 'invoices_vouchers#pending_list'

  resources :states
  resources :voucher_sequences, path: 'voucher-sequences', except: :show

  get '/total-sales-summary' => 'total_sales_summary#show'
  get '/total-sales-summary-report' => 'total_sales_summary#constructdatatable'
  post '/total-sales-summary-validate' => 'total_sales_summary#validate_negative_sales'
  get '/on-hand-lookup' => 'on_hand_look_up#show'
  get '/on-hand-lookup-report' =>'on_hand_look_up#calculate'
  get '/ping' => 'ping#show'

end

app/models/pos_invoice.rb
class PosInvoice < Invoice

  def entries_account_types
    account_types = entries.account_types
  end

  def destroy_with_children
    ActiveRecord::Base.transaction do
      self.entries.destroy_all
      self.debit_entries.destroy_all
      self.credit_entries.destroy_all
      self.header.destroy
      self.line_items.destroy_all
      self.destroy!
    end
  end

  ### defined in invoice.rb ###
  def payment_mandatory_values_check(attributed)
    if attributed['account_id'].blank? || attributed['amount'].to_i < 1
      # handle new records with invalid data
      return true if attributed['id'].blank?

      # handle existing records with invalid data
      attributed['_destroy'] = true if attributed['id'].present?
    end

    if (attributed['_destroy'].blank? || attributed['_destroy'] == '0' || attributed['_destroy'] == 'false') && Account.find(attributed['account_id'].to_i).type == 'Account::BankAccount'
      attributed['additional_info'] ||= Hash.new
      attributed['additional_info']['bank_name'] = attributed['bank_name']
      attributed['additional_info']['card_last_digits'] = attributed['card_last_digits']
      attributed['additional_info']['expiry_month'] = attributed['expiry_month']
      attributed['additional_info']['expiry_year'] = attributed['expiry_year']
      attributed['additional_info']['mobile_number'] = attributed['mobile_number']
      attributed['additional_info']['card_holder_name'] = attributed['card_holder_name']
    end
    false
  end
  ### end of defined in invoice.rb ###
end

app/controllers/pos_invoices_controller.rb
class PosInvoicesController < ApplicationController
  power :pos_invoices, map: {
      [:edit, :update, :get_voucher_sequences] => :updatable_pos_invoices,
      [:new, :create, :get_voucher_sequences] => :creatable_pos_invoices,
      [:index, :show] => :view_pos_invoices,
      [:destroy] => :destroyable_pos_invoices
  }, as: :pos_invoice_scope
  include VoucherSequenceable
  before_action :set_pos_invoice, only: [:edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      # format.csv { send_data @pos_invoices.to_csv, filename: "sale_transactions_complete_#{Time.zone.now.in_time_zone.strftime('%Y%m%d')}.csv" }
      format.xls #{ send_data @pos_invoices.to_csv(col_sep: "\t"), filename: "sale_transactions_complete_#{Time.zone.now.in_time_zone.strftime('%Y%m%d')}.xls" }
      format.json { render json: PosInvoiceDatatable.new(view_context) }
    end
  end

  def show
    @pos_invoice = pos_invoice_scope.includes([line_items: [product: :language]], :created_by).find(params[:id])
    respond_to do |format|
      format.html #{ redirect_to pos_invoice(@pos_invoice.id) }
      format.pdf do
        pdf = PosInvoicePdf.new(@pos_invoice)
        send_data pdf.render, filename: "pos_invoice_#{@pos_invoice.number}",
                  type: "application/pdf",
                  disposition: 'inline'
      end
    end
  end

  def new
    @pos_invoice = PosInvoice.new({txn_date: Time.zone.now.in_time_zone.strftime('%d/%m/%Y')})
    initialize_form
  end

  def edit
    initialize_form
  end

  def create
    @pos_invoice = PosInvoice.new(pos_invoice_params.merge!(current_user_id: current_user.id)) #, current_business_entity: current_business_entity))

    respond_to do |format|
      if @pos_invoice.save
        initialize_form
        # Temp workaround, this needs to be changed.
        # format.html { redirect_to pos_invoice_path(@pos_invoice.id), flash: {success: 'POS invoice was created successfully.'}}
        format.html { redirect_to pos_invoice_path(@pos_invoice.id) }
        format.json { render :show, status: :created, location: @pos_invoice }
      else
        initialize_form
        format.html { render :new }
        format.json { render json: @pos_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pos_invoice.update(pos_invoice_params.merge!(current_user_id: current_user.id))
        format.html { redirect_to pos_invoice_url(@pos_invoice.id), flash: {success: 'POS invoice was updated successfully.'} }
        format.json { render :show, status: :ok, location: @pos_invoice }
      else
        initialize_form
        format.html { render :edit }
        format.json { render json: @pos_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pos_invoice.destroy_with_children
    respond_to do |format|
      format.html { redirect_to pos_invoices_url, notice: 'POS invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def pos_invoice_params
    params.require(:pos_invoice).permit(:business_entity_id, :currency_id,
                                        :voucher_sequence_id, :created_by_id,
                                        :remarks, :txn_date, :status, :ref_number,
                                        debit_entries_attributes: [:id, :account_id, :amount,
                                                                   :remarks, :bank_name, :card_last_digits,
                                                                   :expiry_month, :expiry_year, :mobile_number,
                                                                   :card_holder_name, :_destroy, :mode],
                                        credit_entries_attributes: [:id, :account_id, :amount,
                                                                    :remarks, :bank_name, :card_last_digits,
                                                                    :expiry_month, :expiry_year, :mobile_number,
                                                                    :card_holder_name, :_destroy],
                                        header_attributes: [:id, :address, :legal_details,
                                                            :customer_membership_number,
                                                            :business_entity_location_id],
                                        line_items_attributes: [:id, :product_id,
                                                                :quantity, :price, :goods_value, :tax_rate,
                                                                :tax_amount, :amount, :state_category_tax_rate_id,
                                                                :_destroy]
    )
    #:tax_amount is not included in pos_invoice or line_items as it will be calculated by server
  end

  def set_pos_invoice
    @pos_invoice = pos_invoice_scope.includes(:line_items, :header, :debit_entries, :credit_entries).find(params[:id])
  end

  def populate_tax_slabs
  end

  def populate_products
    @products ||= Product.includes([:language, :category]).active.order(:sku)
  end

  def build_child_line_items
    rec_count = @pos_invoice.line_items.size
    if rec_count < 4
      (15 - rec_count).times { @pos_invoice.line_items.build }
    else
      4.times { @pos_invoice.line_items.build }
    end
  end

  def build_payment_children
    user_cash_account_id = current_user.cash_account_id

    debit_payments = @pos_invoice.debit_entries.payment_entries
    if debit_payments.blank? || debit_payments.collect(&:mode).exclude?('Account::CashAccount')
      @pos_invoice.debit_entries.build(account_id: current_user.cash_account_id, mode: current_user.cash_account.type) if current_user.cash_account_id.present?
    end
    if debit_payments.blank? || debit_payments.collect(&:mode).exclude?('Account::BankAccount')
      @pos_invoice.debit_entries.build(account_id: BusinessEntityLocation.find(GlobalSettings.current_bookstall_id).bank_account_id, mode: BusinessEntityLocation.find(GlobalSettings.current_bookstall_id).bank_account.type) if BusinessEntityLocation.find(GlobalSettings.current_bookstall_id).bank_account_id.present?
    end

    credit_payments = @pos_invoice.credit_entries.payment_entries
    if credit_payments.blank? || credit_payments.collect(&:mode).exclude?('Account::CashAccount')
      @pos_invoice.credit_entries.build(account_id: current_user.cash_account_id, mode: current_user.cash_account.type) if current_user.cash_account_id.present?
    end
  end

  def build_header
    @pos_invoice.build_header(business_entity_location_id: GlobalSettings.current_bookstall_id) if @pos_invoice.header.blank?
  end

  def initialize_form
    populate_tax_slabs
    populate_products
    build_header
    build_child_line_items
    build_payment_children
  end


end

app/views/pos_invoices/_form.html.erb
<%= form_for @pos_invoice do |f| %>
    <div class='row'>
      <%= render 'layouts/error_messages', object: f.object %>
      <div class='col-md-9'>

        <div class='row'>
          <div>
            <div class="col-md-2 text-center">
              <div class="form-group">
                <%= f.label :invoice_date, 'Date' %>
                <%= f.text_field :txn_date, value: (f.object.txn_date.strftime('%d/%m/%Y') if f.object.txn_date), class: 'datetimepicker text-center form-control', tabindex: '-1', required: 'true', readonly: true %>
              </div>
            </div>

            <%= f.fields_for :header do |fh| %>
                <div class="col-md-3">
                  <div class='form-group text-center'>
                    <%= fh.label :business_entity_location_id, 'Entity :: Location' %>
                    <% if @current_user.role?(['admin', 'power_user', 'hq_staff']) %>
                        <%= fh.collection_select :business_entity_location_id, BusinessEntityLocation.own_locations.includes(:business_entity).active_n_current(fh.object.business_entity_location_id).order("business_entities.alias_name"), :id, :entity_name_with_location,
                                                 {include_blank: true},
                                                 {class: 'form-control selectme', id: 'primary_location'} %>
                    <% else %>
                        <%= fh.collection_select :business_entity_location_id, BusinessEntityLocation.own_locations.includes(:business_entity).active_n_current(fh.object.business_entity_location_id).order("business_entities.alias_name"), :id, :entity_name_with_location,
                                                 {readonly: true}, {class: 'form-control selectme', id: 'primary_location'} %>
                    <% end %>
                  </div>
                </div>

                <div class='col-md-2'>
                  <div class="form-group text-center">
                    <%= fh.label :customer_membership_number, 'ID Card #' %><br>
                    <%= fh.text_field :customer_membership_number, class: 'form-control', id: 'customer_membership_number', autofocus: true %>
                  </div>
                </div>
            <% end %>

            <div class='col-md-2'>
              <div class="form-group text-center">
                <%= f.label :number %><br>
                <%= f.text_field :number,
                                 value: ((f.object.number == 0 || f.object.blank?) ? 'New' : f.object.number),
                                 class: 'form-control text-center', tabindex: '-1', readonly: true %>
              </div>
            </div>

            <div class="col-md-1 text-center">
              <div class="form-group">
                <%= label_tag 'T. Qty.' %>
                <%= label_tag '0', nil, class: 'form-control text-center products_count', disabled: true %>
              </div>
            </div>

            <div class='col-md-2 text-center'>
              <div class='form-group'>
                <%= label_tag 'Amount' %>
                <%= label_tag '0.00', nil, id: 'voucher_amount', class: 'form-control text-center', disabled: true %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class='col-md-3'>
        <h2 class='text-center' style='margin-bottom:5px;'>
          Payment Details
        </h2>
      </div>
    </div>

    <div class='row'>
      <div class='col-md-9'>
        <hr style='margin-top:0px;margin-bottom:5px;border-color:black'>
      </div>
      <div class='col-md-3'>
        <hr style='margin-top:0px;margin-bottom:5px;border-color:black'>
      </div>
    </div>

    <div class='row'>
      <div class='col-md-9'>
        <%# cache [@pos_invoice, "pos_invoice_line_items"] do %>
        <div class="table-responsive table-striped table-hover">
          <table id='voucher_line_items' class='voucher_line_items_table'>
            <thead>
            <tr style='height:30px;'>
              <th class="col-md-2 text-center">SKU</th>
              <th class="col-md-5 text-center">Product</th>
              <th class="col-md-1 text-center">Qty</th>
              <th class="col-md-1 text-center">Rate</th>
              <th class="col-md-2 text-center">Amount</th>
            </tr>
            </thead>
            <tbody>
            <%= f.fields_for :line_items do |f_line_item| %>
                <tr class="fields">
                  <td><%= select "#{f_line_item.object_name}", 'sku', @products.map { |x| [x.sku.to_i, x.id] }, {include_blank: true}, class: 'form-control selectme text-center voucher_line_item_sku' %></td>
                  <td><%= f_line_item.collection_select :product_id, @products, :id, :voucher_label,
                                                        {include_blank: true}, {class: 'form-control selectme voucher_line_item_product'} %></td>
                  <td>
                    <%= f_line_item.text_field :quantity, value: (-f_line_item.object.quantity if f_line_item.object.quantity), class: 'form-control text-center voucher_line_item_quantity', type: 'number', min: 0 %>
                  </td>
                  <td><%= f_line_item.text_field :price, class: 'form-control text-center voucher_line_item_rate', tabindex: '-1', min: 0, readonly: true %></td>
                  <td style='padding-right:0px;'>
                    <%= f_line_item.text_field :amount, class: 'form-control text-center voucher_line_item_amount', tabindex: '-1', min: 0, readonly: true, style: 'width:80%;float:left;' %>
                    <%= link_to "", '#', class: "voucher_line_item_remove fa fa-trash-o fa-lg fa-td", tabindex: '-1' %>
                    <%= f_line_item.hidden_field :_destroy, size: '5x5', class: 'line_item_destroy' %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <%# end %>
        <div class="form-group" style='margin-top:5px;'>
          <div class='row'>
            <div class='col-md-3'>
              <%= f.label :ref_number, 'Ref #' %><br>
              <%= f.text_field :ref_number, class: 'form-control' %>
            </div>
            <div class='col-md-9'>
              <%= f.text_area :remarks, class: 'form-control', rows: 2, type: 'text',
                              placeholder: 'Remarks', tabindex: '-1' %>
            </div>
          </div>
        </div>
      </div>
      <div class='col-md-3'>
        <%= render 'pos_invoices/payments/form', f: f %>
        <div class='row'>
          <div class='col-md-4' style='padding-left:10px;padding-right:5px;'>
            <%= f.submit "Save", class: 'btn btn-primary btn-block', id: 'save_button' %>
          </div>
          <div class='col-md-4' style='padding-left:0px;padding-right:0px;'>
            <%= link_to 'List of invoices', pos_invoices_url, :class => 'btn btn-primary btn-block' %>
          </div>
          <div class='col-md-4' style='padding-left:5px;padding-right:10px;'>
            <%= link_to 'Delete', f.object, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-primary btn-block' if f.object.persisted? && current_power.destroyable_pos_invoice?(f.object) %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/pos_invoices/edit.html.erb
<% provide(:title, 'Edit POS Invoice') %>
<%= render 'form' %>

app/views/pos_invoices/index.html.erb
<% provide(:title, 'POS Invoice listing') %>
<%= link_to 'New Sale invoice', new_pos_invoice_path, class: 'pull-right' %>
<div class="display responsive no-wrap voucher_line_items">
  <table id='pos_invoice_index' , data-source="<%= pos_invoices_url(format: :json) %>" , class='DataTable-line-items'>
    <thead>
    <tr>
      <th class='col-md-1 text-center'>Date</th>
      <th class='col-md-1 text-center'>Invoice #</th>
      <th class='col-md-2 text-center'>Entity </th>
      <th class='col-md-2 text-center'>Location </th>
      <th class='col-md-1 text-center'>Amount</th>
      <th class='col-md-2 text-center'>Created by </th>
      <th class='col-md-2 text-center'>Operations</th>
    </tr>
    </thead>
    <tbody>
    <%# @pos_invoices.find_each do |pos_invoice| %>
    <!-- <tr>
          <td class='text-center'><%#= pos_invoice.txn_date.strftime('%d/%m/%Y') %></td>
          <td class='text-center'><%#= pos_invoice.number %></td>
          <td class='text-center'>
            <%#= pos_invoice.location.entity_name_with_location %>
          </td>
          <td class='text-center'><%#= pos_invoice.entries.sales_total_amount %></td>
          <td class='text-center'><%#= pos_invoice.created_by.custom_object_label %></td>
          <td class='text-center'><%##= link_to 'Show', pos_invoice %>
            <%#= link_to "PDF version", pos_invoice_url(pos_invoice.id, format: "pdf"), target: :_blank %> | <%#= link_to 'Edit', edit_pos_invoice_path(pos_invoice.id) if current_power.include_record?(:updatable, pos_invoice) %>
          </td>
        </tr> -->
    <%# end %>
    </tbody>
  </table>
</div>


<script>
  $(function () {
    var dt = $('#pos_invoice_index').dataTable({
      processing: true,
      serverSide: true,
      ajax: $('#pos_invoice_index').data('source'),
      aLengthMenu: [[15, 30, 60, 120, 240], [15, 30, 60, 120, 240]],
      pagingType: 'full_numbers',
      order: [[0, "desc"], [1, "desc"]],
      sPaginationType: "bootstrap",
      columns: [
        {"sClass": "text-center"},
        {"sClass": "text-center"},
        {"sClass": "text-center", "sortable": false},
        {"sClass": "text-center"},
        {"sClass": "text-right", "sortable": false},
        {"sClass": "text-center"},
        {"sClass": "text-center", "sortable": false}
      ]
    });

    $('#date_search').keyup(function () {
      dt.column(0).search(this.value).draw();
    });
    $('#entity_search').keyup(function () {
      dt.column(2).search(this.value).draw();
    });
    $('#location_search').keyup(function () {
      dt.column(3).search(this.value).draw();
    });
    $('#invoice_search').keyup(function () {
      dt.column(1).search(this.value).draw();
    });

    $('#created_search').keyup(function () {
      dt.column(5).search(this.value).draw();
    });

  });
</script>

app/views/pos_invoices/index.xls.erb
<table border='1'>
  <thead>
    <tr>
      <th>Date</th>
      <th>Invoice #</th>
      <th>SKU</th>
      <th>Product Name</th>
      <th>Cat. Code</th>
      <th>Lang. Code</th>
      <th>Qty</th>
      <th>Rate</th>
      <th>Amount</th>
    </tr>
  </thead>

  <tbody>
    <% @pos_invoices.rows_for_export.each do |details| %>
      <tr>
        <td><%= details[0] %></td>
        <td><%= details[1] %></td>
        <td><%= details[2] %></td>
        <td><%= details[3] %></td>
        <td><%= details[4] %></td>
        <td><%= details[5] %></td>
        <td><%= details[6] %></td>
        <td><%= details[7] %></td>
        <td><%= details[8] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pos_invoices/new.html.erb
<% provide(:title, 'New Invoice') %>
<%= render 'form' %>

app/views/pos_invoices/show.html.erb
<h2 class='text-center'><%= GlobalSettings.organisation_name %></h2>
<p class='text-center'>
  <%= GlobalSettings.organisation_address %><br>
  <%= GlobalSettings.organisation_registration %>
</p>
<hr>

<h3 class='text-center'><%= "POS Invoice ##{@pos_invoice.number}" %></h3>
<p><%= "Dated: #{@pos_invoice.txn_date.strftime('%d/%m/%Y')}" %></p>

<table style='width: 100%;'>
  <thead>
    <tr>
      <th class='col-md-2 text-center'>SKU</th>
      <th class='col-md-4 text-center'>Product</th>
      <th class='col-md-2 text-center'>Qty</th>
      <th class='col-md-2 text-center'>Price</th>
      <th class='col-md-2 text-center'>Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @pos_invoice.line_items.map do |item| %>
      <% next if !item.persisted? %>
      <tr>
        <td class='text-center'><%= item.product.sku %></td>
        <td><%= item.voucher_print_name %></td>
        <td class='text-center'><%= -item.quantity %></td>
        <td class='text-center'><%= sprintf '%.0f', item.selling_price %></td>
        <td class='text-center'><%= sprintf '%.0f', item.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3><%= "Total Amount: #{(sprintf '%.2f', @pos_invoice.credit_entries.sales_total_amount)}" %><br>
<%= "Total Quantity: #{@pos_invoice.total_quantity}" %><br>
<%= "Payment Details:" %></h3>
<p>
  <% @pos_invoice.payments_order_type_desc.each do |payment| %>
    <% next if payment.new_record? %>
    <%= payment.type == 'AccountEntry::Debit' ? "Cash: #{(sprintf '%.2f', payment.amount)}" : "Cash Tendered: #{(sprintf '%.2f', payment.amount)}" if payment.mode == 'Account::CashAccount' %>
    <% if payment.mode == 'Account::BankAccount' && payment.additional_info.present? %>
      <%= "Bank Name: #{payment.additional_info['bank_name']}" %>
      <%= "Card last 4 digits: #{payment.additional_info['card_last_digits']}" %>
      <%= "Expiry month/year: #{payment.additional_info['expiry_month']} / #{payment.additional_info['expiry_year']}" %>
      <%= "Mobile Number: #{payment.additional_info['mobile_number']}" %>
      <%= "Card Holder's Name: #{payment.additional_info['card_holder_name']}" %>
    <% end %>
  <% end %>
</p>
<p>
  <%= "You were served by: #{@pos_invoice.created_by.name}" %>
  <%= "Prices are inclusive of taxes" %>
</p>

<%= link_to("Print invoice", "javascript:window.print()", id: 'print_invoice') %><br>
<%= link_to 'New Invoice', new_pos_invoice_url, id: 'open_new_invoice' %><br>
<%= link_to "Printable Receipt (PDF)", pos_invoice_path(@pos_invoice.id, format: "pdf"), target: :_blank, id: 'pdf_print' %><br>
<%= link_to 'Edit', edit_pos_invoice_path(@pos_invoice) if current_power.updatable_pos_invoice?(@pos_invoice) %><br>
<%= link_to 'Invoices Listing', pos_invoices_path %><br>
<%= link_to 'Delete', @pos_invoice, method: :delete, data: { confirm: 'Are you sure?' } if current_power.destroyable_pos_invoice?(@pos_invoice) %><br>